apiVersion: v1
kind: Service
metadata:
  labels:
    app: cache-server
    application-crd-id: kubeflow-pipelines
  name: cache-server
  namespace: kubeflow
spec:
  ports:
    - port: 443
      targetPort: webhook-api
  selector:
    app: cache-server
    application-crd-id: kubeflow-pipelines