matrix:
  include:
    - language: go
      go: 1.8.x
      sudo: required
      before_script:
        - sudo pip install pre-commit
        - curl https://glide.sh/get | bash
      script: 
        - | 
          bash .tools/check_style.sh
          RESULT=$?; if [ $RESULT -eq 0 ] then true; else false; fi;
        - bash .tools/gen_config.sh && cd go && glide install && go test $(glide novendor)
    - language: python
      python: 2.7
      sudo: required
      env:
        - DJANGO_SETTINGS_MODULE="paddlecloud.travis_settings"
      before_script:
        - mysql -e 'create database paddlecloud;'
        - mkdir $HOME/.kube && cp ./k8s/config $HOME/.kube/
        - pip install -r paddlecloud/requirements.txt
        - cd paddlecloud && python manage.py migrate
      script:
        - python manage.py test
