apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: paddle-cloud
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: paddle-cloud
    spec:
      volumes:
      - name: cert-volume
        hostPath:
          path: /root/wuyi/certs
      - name: settings
        hostPath:
          path: /root/wuyi/settings.py
      - name: mysql-data
        hostPath:
          path: /root/wuyi/mysql
      containers:
      - name: paddle-cloud
        imagePullPolicy: Always
        image: docker.paddlepaddlehub.com/pcloud:wuyi_test
        volumeMounts:
        - name: cert-volume
          mountPath: /certs
        - name: settings
          mountPath: /pcloud/paddlecloud/settings.py
        ports:
        - containerPort: 8000
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CLOUD_DOMAIN
          value: "cloud.paddlepaddle.org"
        livenessProbe:
         httpGet:
           path: /healthz/
           port: 8000
           httpHeaders:
           - name: User-Agent
             value: kubernetes-health-check
         initialDelaySeconds: 3
         periodSeconds: 5
      - name: mysql
        image: mysql:5.7
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
      nodeSelector:
        pcloud: pcloud
