
---
# Activator PDB. Currently we permit unavailability of 20% of tasks at the same time.
# Given the subsetting and that the activators are partially stateful systems, we want
# a slow rollout of the new versions and slow migration during node upgrades.
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: activator-pdb
  namespace: knative-serving
  labels:
    serving.knative.dev/release: "v0.21.1"
spec:
  minAvailable: 80%
  selector:
    matchLabels:
      app: activator
