# Default values for juicefs-csi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Overrides the chart's computed name
# nameOverride: ""
# -- Overrides the chart's computed fullname
# fullnameOverride: ""

namespace: kube-system

image:
  repository: juicedata/juicefs-csi-driver
  tag: "v0.12.0"
  pullPolicy: ""

sidecars:
  livenessProbeImage:
    repository: quay.io/k8scsi/livenessprobe
    tag: "v1.1.0"
  nodeDriverRegistrarImage:
    repository: quay.io/k8scsi/csi-node-driver-registrar
    tag: "v1.1.0"
  csiProvisionerImage:
    repository: quay.io/k8scsi/csi-provisioner
    tag: "v1.6.0"

# for some environment without dns server and want to use /etc/hosts instead
# - ip: "127.0.0.1"
#   hostnames:
#   - "s3.juicefs.local"
#   - "redis.juicefs.local"
hostAliases: []

# -- kubelet working directory,can be set using `--root-dir` when starting kubelet
kubeletDir: /var/lib/kubelet

# -- juicefs mount dir
jfsMountDir: /var/lib/juicefs/volume
jfsConfigDir: /var/lib/juicefs/config

dnsPolicy: ClusterFirstWithHostNet
dnsConfig:
  {}
  # Example config which uses the AWS nameservers
  # dnsPolicy: "None"
  # dnsConfig:
  #   nameservers:
  #     - 169.254.169.253

serviceAccount:
  controller:
    # Specifies whether a service account of controller should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: "juicefs-csi-controller-sa"
  node:
    # Specifies whether a service account of node service should be created
    create: true
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: "juicefs-csi-node-sa"

controller:
  # Default is true. This Component will control CSI Driver deployed on node
  enabled: true
  # Pod Numbers
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  # -- Grace period to allow the controller to shutdown before it is killed
  terminationGracePeriodSeconds: 30
  # -- Affinity for controller pods.
  # @default -- Hard node and soft zone anti-affinity
  affinity: {}
  # -- Node selector for controller pods
  nodeSelector: {}
  # -- Tolerations for controller pods
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
  # controller service
  service:
    port: 9909
    trpe: ClusterIP

node:
  # Default is true. Node will be deployed every node to server CSI Plugin
  enabled: true
  hostNetwork: false
  resources:
    limits:
      cpu: 2000m
      memory: 5Gi
    requests:
      cpu: 1000m
      memory: 1Gi
  # -- Grace period to allow the node pod to shutdown before it is killed
  terminationGracePeriodSeconds: 30
  # -- Affinity for node pods.
  # @default -- Hard node and soft zone anti-affinity
  affinity: {}
  # -- Node selector for node pods
  nodeSelector: {}
  # -- Tolerations for node pods
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists

storageClasses:
  # StorageClass Name. It is important.
- name: juicefs-sc
  # -- Default is true will create a new StorageClass. It will create Secret and StorageClass used by CSI driver
  enabled: true
  # -- Either Delete or Retain.
  reclaimPolicy: Delete

  backend:
    # -- The JuiceFS file system name.
    name: "juice"
    # -- Connection URL for metadata engine (e.g. Redis). Read [this document](https://github.com/juicedata/juicefs/blob/main/docs/en/databases_for_metadata.md) for more information.
    metaurl: ""
    # -- Object storage type, such as `s3`, `gs`, `oss`. Read [this document](https://github.com/juicedata/juicefs/blob/main/docs/en/how_to_setup_object_storage.md) for the full supported list.
    storage: ""
    # -- Access key for object storage
    accessKey: ""
    # -- Secret key for object storage
    secretKey: ""
    # -- Bucket URL. Read [this document](https://github.com/juicedata/juicefs/blob/main/docs/en/how_to_setup_object_storage.md) to learn how to setup different object storage.
    bucket: ""
    # -- Env for mount pod and format, such as `a: b`
    envs: ""
    # -- Config for mount pod. Read [this document](https://github.com/juicedata/juicefs-csi-driver/blob/master/docs/en/examples/config-and-env.md) for more usage.
    configs: ""
    # -- Config for trash days
    trashDays: ""


  mountOptions:
  # -- Mount Options. Read [this document](https://github.com/juicedata/juicefs/blob/main/docs/en/command_reference.md#juicefs-mount) to learn how to set different mount options.
  # Example:
  # - debug
  # - cache-size=2048
  # - cache-dir=/var/foo

  mountPod:
    # mount pod resource requests & limits
    resources:
      limits:
        cpu: 5000m
        memory: 5Gi
      requests:
        cpu: 1000m
        memory: 1Gi
